spring:
  profiles:
    active: dev
  jackson:
    serialization.indent_output: true
  datasource:
    url: jdbc:mysql://localhost:3306/nintendoshop
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true

    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect